import type { ThemeTemplate } from "@/types";

// Hardcoded fallback themes in case database is unavailable
export const FALLBACK_THEMES: Omit<ThemeTemplate, "id" | "is_active" | "sort_order">[] = [
  {
    slug: "dinosaurs",
    name: "Dinosaur Adventure",
    emoji: "🦕",
    description: "A prehistoric adventure party! Fossil digs, dino eggs, and jungle decorations.",
    color_primary: "#22c55e",
    color_secondary: "#15803d",
    prompt_context: "Theme: Dinosaur Adventure 🦕\nContext: A prehistoric adventure party! Think fossil digs, dino eggs, lush jungle decorations with green/brown palette.\nIconic elements: fossil excavation activity, dino egg hunt, volcano cake, pterodactyl toss game.\nColor scheme: forest green, brown, tan.",
    age_min: 2,
    age_max: 10,
  },
  {
    slug: "princess",
    name: "Royal Princess Ball",
    emoji: "👑",
    description: "A magical royal celebration with tiaras, castles, and enchanted fun.",
    color_primary: "#ec4899",
    color_secondary: "#be185d",
    prompt_context: "Theme: Royal Princess Ball 👑\nContext: A magical royal celebration! Think tiaras, castle decorations, tulle, and glitter.\nIconic elements: crown decorating station, royal decree scroll, princess dress-up, magic wand craft.\nColor scheme: pink, gold, lavender, white.",
    age_min: 3,
    age_max: 10,
  },
  {
    slug: "superhero",
    name: "Superhero Training Camp",
    emoji: "🦸",
    description: "An action-packed hero training adventure with obstacles and missions.",
    color_primary: "#3b82f6",
    color_secondary: "#1d4ed8",
    prompt_context: "Theme: Superhero Training Camp 🦸\nContext: An action-packed hero training adventure! Think obstacle courses, cape making, and villain challenges.\nIconic elements: cape and mask making station, obstacle course, superhero training certificates.\nColor scheme: bold red, blue, yellow with comic-style accents.",
    age_min: 4,
    age_max: 12,
  },
  {
    slug: "sports",
    name: "All-Star Sports Day",
    emoji: "⚽",
    description: "An active sports tournament with mini-games and team spirit.",
    color_primary: "#f97316",
    color_secondary: "#ea580c",
    prompt_context: "Theme: All-Star Sports Day ⚽\nContext: An energetic sports party! Think mini tournaments, team jerseys, and victory celebrations.\nIconic elements: mini tournament bracket, medal ceremony, sports trivia, relay races.\nColor scheme: team colors - green field, white lines, bright accents.",
    age_min: 5,
    age_max: 14,
  },
  {
    slug: "unicorn",
    name: "Magical Unicorn Party",
    emoji: "🦄",
    description: "A rainbow-filled magical celebration with sparkles and enchantment.",
    color_primary: "#a855f7",
    color_secondary: "#7c3aed",
    prompt_context: "Theme: Magical Unicorn Party 🦄\nContext: A rainbow-filled magical celebration! Think pastel colors, sparkles, and enchanted activities.\nIconic elements: unicorn horn headband craft, rainbow ring toss, magical potion making, glitter slime station.\nColor scheme: pastel rainbow - pink, purple, blue, mint with gold accents.",
    age_min: 3,
    age_max: 9,
  },
  {
    slug: "minecraft",
    name: "Minecraft World",
    emoji: "⛏️",
    description: "A pixelated block-building adventure with crafting and exploration.",
    color_primary: "#65a30d",
    color_secondary: "#4d7c0f",
    prompt_context: "Theme: Minecraft World ⛏️\nContext: A pixelated block-building adventure! Think pixel art, TNT, and crafting tables.\nIconic elements: pixel art craft station, creeper target practice, block building challenge, treasure chest hunt.\nColor scheme: Minecraft green, brown (dirt), grey (stone), blue (diamond).",
    age_min: 6,
    age_max: 14,
  },
  {
    slug: "space",
    name: "Outer Space Explorer",
    emoji: "🚀",
    description: "A cosmic journey through the stars with rockets, planets, and alien encounters.",
    color_primary: "#6366f1",
    color_secondary: "#4f46e5",
    prompt_context: "Theme: Outer Space Explorer 🚀\nContext: A cosmic adventure through the galaxy! Think rockets, planets, stars, and astronaut training.\nIconic elements: rocket ship craft, planet painting station, astronaut training obstacle course, alien slime making.\nColor scheme: deep navy, silver, purple with star accents.",
    age_min: 4,
    age_max: 12,
  },
  {
    slug: "ocean",
    name: "Under the Sea",
    emoji: "🐠",
    description: "A deep-sea underwater adventure with marine life and ocean treasures.",
    color_primary: "#06b6d4",
    color_secondary: "#0891b2",
    prompt_context: "Theme: Under the Sea 🐠\nContext: A deep-sea underwater adventure! Think coral reefs, sea creatures, and buried treasure.\nIconic elements: fish craft station, treasure chest hunt, ocean sensory bins, bubble station.\nColor scheme: ocean blue, teal, coral, sandy gold.",
    age_min: 2,
    age_max: 8,
  },
  {
    slug: "construction",
    name: "Construction Zone",
    emoji: "🏗️",
    description: "A building and digging adventure with hard hats and heavy equipment.",
    color_primary: "#eab308",
    color_secondary: "#ca8a04",
    prompt_context: "Theme: Construction Zone 🏗️\nContext: A building and digging adventure! Think hard hats, dump trucks, and construction sites.\nIconic elements: building block challenge, sandbox digging station, hard hat decorating, dump truck relay race.\nColor scheme: construction yellow, orange, black stripes.",
    age_min: 3,
    age_max: 8,
  },
  {
    slug: "safari",
    name: "Wild Safari Adventure",
    emoji: "🦁",
    description: "An exciting jungle safari expedition with wild animals and exploration.",
    color_primary: "#84cc16",
    color_secondary: "#65a30d",
    prompt_context: "Theme: Wild Safari Adventure 🦁\nContext: An exciting jungle safari expedition! Think binoculars, animal prints, and jeep rides.\nIconic elements: animal track identification game, binocular craft, safari scavenger hunt, face painting station.\nColor scheme: safari tan, jungle green, animal prints.",
    age_min: 3,
    age_max: 10,
  },
];

export function getThemeBySlug(slug: string) {
  return FALLBACK_THEMES.find((t) => t.slug === slug) ?? null;
}
